version: '3.9'
services:
  info:
    image: 127.0.0.1:5000/certificates-info
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn prod
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.certificates-info.service=certificates-info
        - traefik.http.routers.certificates-info.entrypoints=web
        - traefik.http.routers.certificates-info.rule=(Host(`certificados.${DOMAIN:-localhost}`))
        - traefik.http.services.certificates-info.loadbalancer.server.port=3000
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    networks:
      - public
networks:
  public:
    external: true
